version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11kfw2w0zz793"
s3_prefix = "resume-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "MyBucketName=\"resume-website\""
